import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>NEXTJS-STRUCTURE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <div>HElLLO WORLD</div>
    </>
  );
}
